import React from 'react'

const Privacy = () => {
  return (
    <div className='lg:mb-20 mb-10 mt-5 lg:mx-40 md:mx-10 mx-6 border border-gray-700 rounded-md'>
    <div className=' flex flex-col justify-center items-center'>
      <p className=' pt-10 md:pb-3 pb-1 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-center  lg:text-[40px] md:text-[30px] text-[20px] font-bold inline-block text-transparent bg-clip-text'>Privacy Policy</p>
      <p className='text-center md:text-[16px] text-[14px] '>Last Updated : January, 2024</p>
     </div>
      <div className='lg:px-40 md:px-10 px-6' >
        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Introduction</p>
        <div className='pt-4'>
        <a href='https://pruthatek.com/' className='pt-4 text-start md:text-[16px] text-[14px]'>Welcome to PruthaTek Pvt. Ltd. This Privacy Policy describes our policies and procedures regarding the collection, use, and disclosure of your information when you use our website [https://pruthatek.com/].</a>
        </div>
        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Interpretation and Definitions</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'><b>Interpretation:</b> The words with the initial letter capitalized have meanings defined under the following conditions. The definitions provided shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'><b>Definition:</b>  For the purposes of this Privacy Policy:</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Account: A unique account created for you to access our Service or parts of our Service.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Company: PruthaTek Pvt. Ltd., referred to as "the Company," "We," "Us," or "Our" in this Agreement. Address: [Your Company Address], [City], [Country].</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Cookies: Small files placed on your computer, mobile device, or any other device by a website, containing details of your browsing history on that website among its many uses.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Device: Any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Personal Data: Any information that relates to an identified or identifiable individual.</p>
        <div className='pt-4'>
        <a href='https://pruthatek.com/' className='pt-4 text-start md:text-[16px] text-[14px]'>Service: Refers to the Website https://pruthatek.com/</a>
        </div>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Service Provider: Any natural or legal person processing data on behalf of the Company, including third-party companies or individuals employed to facilitate the Service or assist the Company in analyzing how the Service is used.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Usage Data:  Data collected automatically, generated by the use of the Service or from the Service infrastructure itself.</p>
        <div className='pt-4'>
        <a href='https://pruthatek.com/' className='pt-4 text-start md:text-[16px] text-[14px]'>Website: Refers to PruthaTek Pvt. Ltd., accessible from https://pruthatek.com/.</a>
        </div>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>You: The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</p>
        
        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Collecting and Using Your Personal Data</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'><b>Types of Data Collected:</b></p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Personal Data: While using our Service, we may ask you to provide personally identifiable information, including but not limited to your email address, first name, last name, and Usage Data.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Usage Data:  Collected automatically, including information such as your device's IP address, browser type, pages visited, time and date of your visit, and other diagnostic data.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Tracking Technologies and Cookies: We use Cookies and similar tracking technologies to track activity on our Service and store certain information.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Use of Your Personal Data: The Company may use Personal Data for various purposes, including providing and maintaining our Service, managing your Account, contacting you, providing news and offers, managing your requests, and other legitimate business purposes.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Disclosure of Your Personal Data: Your personal information may be shared with Service Providers, affiliates, business partners, and in business transfers, among other situations, as outlined in this Privacy Policy.</p>




        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Retention of Your Personal Data</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>  The Company will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.</p>
     
        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Transfer of Your Personal Data</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'> Your information may be processed and maintained at the Company's operating offices and other locations where the parties involved in processing are located.</p>

        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Disclosure of Your Personal Data</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Business Transactions:  If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Law Enforcement:  The Company may disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>Other Legal Requirements:  The Company may disclose your Personal Data in good faith belief that such action is necessary to comply with a legal obligation, protect and defend rights or property, prevent or investigate wrongdoing, or protect personal safety.</p>


        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Security of Your Personal Data</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>  The security of your Personal Data is important to us, and we strive to use commercially acceptable means to protect it. However, no method of transmission over the Internet or electronic storage is 100% secure.</p>

        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Links to Other Websites</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>   Our Service may contain links to other websites not operated by us. We advise you to review the Privacy Policy of every site you visit, as we have no control over and assume no responsibility for the content, privacy policies, or practices of third-party sites.</p>

        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Changes to this Privacy Policy</p>
        <p className='pt-4 text-start md:text-[16px] text-[14px]'>  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

        <p className='pt-8 lg:pt-12 bg-gradient-to-r from-[#F05225] to-[#EEA820] text-start  lg:text-[30px] md:text-[22px] text-[16px] font-bold inline-block text-transparent bg-clip-text'>Contact Us</p>
        <p className='pt-4 pb-8 text-start md:text-[16px] text-[14px]'>  If you have any questions about these Terms and Conditions, You can contact us:<br></br> By email: [Your Contact Email] <br></br> By visiting this page on our website: [Your Contact Page URL]</p>
      
      </div>
      

  </div>
  )
}

export default Privacy
