# Generated by Django 5.0 on 2024-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('product_name', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=10)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Category',
        ),
        migrations.AddField(
            model_name='post',
            name='ads',
            field=models.ManyToManyField(related_name='posts', to='blog.ad'),
        ),
    ]
