# Generated by Django 5.0 on 2024-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_ads_ad_post_alter_ad_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
